# Generated by Django 2.1.1 on 2018-09-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(verbose_name='time requested'),
        ),
    ]
